#!/bin/sh
# Regenerates objects/_index.md from card frontmatter and copies CLAUDE.md to its twins.
# Never hand-edit those three files; run this instead: sh map/_meta/rebuild.sh
# `--check` (run by `pnpm lint`) exits 1 when a generated file is stale or a card cites
# a repo file or line that no longer exists.
set -e
cd "$(dirname "$0")/.."

index() {
  echo "# Objects — one line per noun"
  echo
  echo "Generated by \`_meta/rebuild.sh\` from each card's frontmatter. Open the card, not this list, for anything past the name."
  echo
  echo "| Noun | Cluster | Universe | Status | Owning file |"
  echo "|---|---|---|---|---|"
  for f in objects/*/*.md; do
    cluster=$(sed -n 's/^cluster: //p' "$f" | head -1)
    universe=$(sed -n 's/^universe: //p' "$f" | head -1)
    status=$(sed -n 's/^status: //p' "$f" | head -1)
    entity=$(sed -n 's/^entity: //p' "$f" | head -1)
    title=$(sed -n 's/^# //p' "$f" | head -1)
    echo "| [$title](${f#objects/}) | $cluster | $universe | $status | \`$entity\` |"
  done
}

# Citations that start at a repo root dir (src/, test/, deploy/, ...) must name a real
# file, and every cited line must be inside it. Map-relative and wren paths are skipped.
citations() {
  bad=0
  for c in $(grep -rhoE '`(src|test|ui|deploy|scripts|designs|walkthrough|\.github)/[A-Za-z0-9_./-]+(:[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*)?`' --include='*.md' . | tr -d '`' | sort -u); do
    f=../${c%%:*}
    if [ ! -e "$f" ]; then echo "map: cited file missing: $c"; bad=1; continue; fi
    [ "${c#*:}" = "$c" ] && continue
    n=$(wc -l < "$f")
    for r in $(echo "${c#*:}" | tr ',-' '  '); do
      [ "$r" -le "$n" ] || { echo "map: $c is past the end of the file ($n lines)"; bad=1; }
    done
  done
  return $bad
}

if [ "${1:-}" = "--check" ]; then
  index | cmp -s - objects/_index.md || { echo "map: objects/_index.md is stale, run sh map/_meta/rebuild.sh"; exit 1; }
  for t in AGENTS.md routing.md; do
    cmp -s CLAUDE.md "$t" || { echo "map: $t differs from CLAUDE.md, run sh map/_meta/rebuild.sh"; exit 1; }
  done
  citations
  exit 0
fi

index > objects/_index.md
cp CLAUDE.md AGENTS.md
cp CLAUDE.md routing.md
echo "rebuilt objects/_index.md, AGENTS.md, routing.md"
