#!/bin/sh
# Regenerates objects/_index.md from card frontmatter and copies CLAUDE.md to its twins.
# Never hand-edit those three files; run this instead: sh map/_meta/rebuild.sh
set -e
cd "$(dirname "$0")/.."
{
  echo "# Objects — one line per noun"
  echo
  echo "Generated by \`_meta/rebuild.sh\` from each card's frontmatter. Open the card, not this list, for anything past the name."
  echo
  echo "| Noun | Cluster | Universe | Status | Owning file |"
  echo "|---|---|---|---|---|"
  for f in objects/*/*.md; do
    cluster=$(sed -n 's/^cluster: //p' "$f" | head -1)
    universe=$(sed -n 's/^universe: //p' "$f" | head -1)
    status=$(sed -n 's/^status: //p' "$f" | head -1)
    entity=$(sed -n 's/^entity: //p' "$f" | head -1)
    title=$(sed -n 's/^# //p' "$f" | head -1)
    echo "| [$title](${f#objects/}) | $cluster | $universe | $status | \`$entity\` |"
  done
} > objects/_index.md
cp CLAUDE.md AGENTS.md
cp CLAUDE.md routing.md
echo "rebuilt objects/_index.md, AGENTS.md, routing.md"
